name: holoviews-contrib

channels:
  - ioam/label/dev
  - defaults

dependencies:
  - python
  - holoviews>=1.7dev2
  - numpy
  - pyzmq
  - jinja2
  - tornado
  - jsonschema
  - pygments
  - notebook
  - matplotlib
  - pandas
  - seaborn
  - mpld3
  - bokeh
  - nose
  - pip:
    -  cyordereddict
